<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SiswaTableSeeder extends Seeder
{

    public function run()
    {


        DB::table('siswa')->delete();

        DB::table('siswa')->insert(array (
            0 =>
            array (
                'alamat' => 'Dadapan-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 1,
                'jenis_kelamin' => 'Laki-Laki',
                'jurusan' => 2,
                'kelas' => 'Kelas XI',
                'nama_siswa' => 'Ahmad Hafidz Saifullah',
                'no_induk' => '3036911455',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2003-06-04',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'Shofiyatul Hikmah',
            ),
            1 =>
            array (
                'alamat' => 'Dadapan-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 2,
                'jenis_kelamin' => 'Laki-Laki',
                'jurusan' => 2,
                'kelas' => 'Kelas XI',
                'nama_siswa' => 'Ahmad Wildan Ittaqillah',
                'no_induk' => '0003372361',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2000-06-23',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'Siti Asiyah',
            ),
            2 =>
            array (
                'alamat' => 'Dadapan-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 3,
                'jenis_kelamin' => 'Laki-Laki',
                'jurusan' => 2,
                'kelas' => 'Kelas X',
                'nama_siswa' => 'Alvian Bhakti Setiawan',
                'no_induk' => '0021816405',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2002-12-20',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'Utik Suraliningtyas',
            ),
            3 =>
            array (
                'alamat' => 'Dadapan-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 4,
                'jenis_kelamin' => 'Perempuan',
                'jurusan' => 2,
                'kelas' => 'Kelas XI',
                'nama_siswa' => 'ANINDIA SAFITRI HIDAYAH',
                'no_induk' => '0029557800',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2013-12-15',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'SATIUL HIDAYATI',
            ),
            4 =>
            array (
                'alamat' => 'Dadapan-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 5,
                'jenis_kelamin' => 'Perempuan',
                'jurusan' => 2,
                'kelas' => 'Kelas XII',
                'nama_siswa' => 'Dwi Kananda Maulidia Damayanti',
                'no_induk' => '0022072376',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2002-05-18',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'Anis Faulutfiyah',
            ),
            5 =>
            array (
                'alamat' => 'Dadapan-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 6,
                'jenis_kelamin' => 'Perempuan',
                'jurusan' => 2,
                'kelas' => 'Kelas XII',
                'nama_siswa' => 'Enmah intan Nur laila',
                'no_induk' => '0086880476',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2002-03-31',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'ENAWATI',
            ),
            6 =>
            array (
                'alamat' => 'Dadapan-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 7,
                'jenis_kelamin' => 'Laki-Laki',
                'jurusan' => 2,
                'kelas' => 'Kelas XII',
                'nama_siswa' => 'Fajar Aditya Brahmana Saputra',
                'no_induk' => '0015893560',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2001-11-09',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'Sri Utami',
            ),
            7 =>
            array (
                'alamat' => 'Dadapan-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 8,
                'jenis_kelamin' => 'Laki-Laki',
                'jurusan' => 2,
                'kelas' => 'Kelas X',
                'nama_siswa' => 'Fikar Rohmatulloh',
                'no_induk' => '0036795050',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2003-02-18',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'Sujanah',
            ),
            8 =>
            array (
                'alamat' => 'Dadapan-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 9,
                'jenis_kelamin' => 'Perempuan',
                'jurusan' => 2,
                'kelas' => 'Kelas XII',
                'nama_siswa' => 'Gea Amanda',
                'no_induk' => '0021877076',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2002-05-02',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'Sukarlik',
            ),
            9 =>
            array (
                'alamat' => 'Dadapan-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 10,
                'jenis_kelamin' => 'Laki-Laki',
                'jurusan' => 2,
                'kelas' => 'Kelas XI',
                'nama_siswa' => 'Gilang Purnama Ainul Haq',
                'no_induk' => '0022071443',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2002-05-10',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'Lasiyatin',
            ),
            10 =>
            array (
                'alamat' => 'Dadapan-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 11,
                'jenis_kelamin' => 'Perempuan',
                'jurusan' => 2,
                'kelas' => 'Kelas X',
                'nama_siswa' => 'IIF SYARIFAH',
                'no_induk' => '0025190034',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2002-05-02',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'LUTFIYAH',
            ),
            11 =>
            array (
                'alamat' => 'Dadapan-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 12,
                'jenis_kelamin' => 'Perempuan',
                'jurusan' => 2,
                'kelas' => 'Kelas XI',
                'nama_siswa' => 'Irfana Rahmaniyah',
                'no_induk' => '0032771846',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2003-06-25',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'Shofiyah',
            ),
            12 =>
            array (
                'alamat' => 'Dadapan-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 13,
                'jenis_kelamin' => 'Laki-Laki',
                'jurusan' => 2,
                'kelas' => 'Kelas XII',
                'nama_siswa' => 'Khafsin Asrori',
                'no_induk' => '0015893559',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2001-10-09',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'Sulasri',
            ),
            13 =>
            array (
                'alamat' => 'Dadapan-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 14,
                'jenis_kelamin' => 'Laki-Laki',
                'jurusan' => 2,
                'kelas' => 'Kelas X',
                'nama_siswa' => 'Khoirul Hadi Taqiyudin',
                'no_induk' => '0043636312',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2004-09-26',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'Anik Nur Kholis',
            ),
            14 =>
            array (
                'alamat' => 'Dadapan-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 15,
                'jenis_kelamin' => 'Perempuan',
                'jurusan' => 2,
                'kelas' => 'Kelas X',
                'nama_siswa' => 'Kis\'atin Nuroh',
                'no_induk' => '0033000632',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2003-09-06',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'Sukaini',
            ),
            15 =>
            array (
                'alamat' => 'Dadapan-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 16,
                'jenis_kelamin' => 'Perempuan',
                'jurusan' => 2,
                'kelas' => 'Kelas XI',
                'nama_siswa' => 'LAILATUL EKA NURMALA ALAFIA',
                'no_induk' => '0022472754',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2002-10-03',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'MUNAFIAH',
            ),
            16 =>
            array (
                'alamat' => 'Dadapan-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 17,
                'jenis_kelamin' => 'Laki-Laki',
                'jurusan' => 2,
                'kelas' => 'Kelas XI',
                'nama_siswa' => 'Leo Diva Arianto',
                'no_induk' => '0032771910',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2003-03-29',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'Maratus Sholihah',
            ),
            17 =>
            array (
                'alamat' => 'Dadapan-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 18,
                'jenis_kelamin' => 'Laki-Laki',
                'jurusan' => 2,
                'kelas' => 'Kelas XII',
                'nama_siswa' => 'M. ARIF FURQON',
                'no_induk' => '0015891943',
                'status_aktif' => 'Keluar',
                'status_lulus' => NULL,
                'tanggal_keluar' => '2020-07-07',
                'tanggal_lahir' => '2002-10-16',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'CHOLIFAH',
            ),
            18 =>
            array (
                'alamat' => 'Dadapan-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 19,
                'jenis_kelamin' => 'Laki-Laki',
                'jurusan' => 2,
                'kelas' => 'Kelas XII',
                'nama_siswa' => 'M. Azmi Naufal',
                'no_induk' => '0022072393',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2002-10-12',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'Titim Muhimmah',
            ),
            19 =>
            array (
                'alamat' => 'Dadapan-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 20,
                'jenis_kelamin' => 'Laki-Laki',
                'jurusan' => 2,
                'kelas' => 'Kelas XI',
                'nama_siswa' => 'M. Hasbullah',
                'no_induk' => '0000608735',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2000-08-15',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'Qibtiatun',
            ),
            20 =>
            array (
                'alamat' => 'Tebluru-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 21,
                'jenis_kelamin' => 'Laki-Laki',
                'jurusan' => 2,
                'kelas' => 'Kelas XII',
                'nama_siswa' => 'M. Kamaluddin',
                'no_induk' => '0025160358',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2002-06-05',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'Shofiatul Ummah',
            ),
            21 =>
            array (
                'alamat' => 'Tebluru-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 22,
                'jenis_kelamin' => 'Laki-Laki',
                'jurusan' => 2,
                'kelas' => 'Kelas X',
                'nama_siswa' => 'M. MUSHLIHIN',
                'no_induk' => '0043636304',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2004-06-18',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'Kusmiati',
            ),
            22 =>
            array (
                'alamat' => 'Tebluru-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 23,
                'jenis_kelamin' => 'Laki-Laki',
                'jurusan' => 2,
                'kelas' => 'Kelas XI',
                'nama_siswa' => 'M. Mustaqim',
                'no_induk' => '0036222944',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2003-06-03',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'Warlin',
            ),
            23 =>
            array (
                'alamat' => 'Tebluru-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 24,
                'jenis_kelamin' => 'Laki-Laki',
                'jurusan' => 2,
                'kelas' => 'Kelas XII',
                'nama_siswa' => 'M. ROFI\'UL HIMAM',
                'no_induk' => '0018186120',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2001-10-24',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'NUR AFIDAH',
            ),
            24 =>
            array (
                'alamat' => 'Tebluru-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 25,
                'jenis_kelamin' => 'Laki-Laki',
                'jurusan' => 2,
                'kelas' => 'Kelas XII',
                'nama_siswa' => 'Mahardika Putra Arianto',
                'no_induk' => '0011971146',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2001-08-04',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'Karsitah',
            ),
            25 =>
            array (
                'alamat' => 'Tebluru-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 26,
                'jenis_kelamin' => 'Perempuan',
                'jurusan' => 2,
                'kelas' => 'Kelas XI',
                'nama_siswa' => 'Mar\'tun Najiyah',
                'no_induk' => '0036591623',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2003-05-23',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'Luluk Anisatul Hamidah',
            ),
            26 =>
            array (
                'alamat' => 'Tebluru-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 27,
                'jenis_kelamin' => 'Perempuan',
                'jurusan' => 2,
                'kelas' => 'Kelas X',
                'nama_siswa' => 'Mawar Umu Salamah',
                'no_induk' => '0043860081',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2004-11-16',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'Siti Rohmawati',
            ),
            27 =>
            array (
                'alamat' => 'Tebluru-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 28,
                'jenis_kelamin' => 'Perempuan',
                'jurusan' => 2,
                'kelas' => 'Kelas XI',
                'nama_siswa' => 'Miftakhun Nikmah',
                'no_induk' => '0036528396',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2003-01-07',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'Nasri',
            ),
            28 =>
            array (
                'alamat' => 'Tebluru-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 29,
                'jenis_kelamin' => 'Laki-Laki',
                'jurusan' => 2,
                'kelas' => 'Kelas XI',
                'nama_siswa' => 'Misbahul Munir',
                'no_induk' => '0035988425',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2003-12-19',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'Siti Rokhimi',
            ),
            29 =>
            array (
                'alamat' => 'Tebluru-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 30,
                'jenis_kelamin' => 'Laki-Laki',
                'jurusan' => 2,
                'kelas' => 'Kelas XII',
                'nama_siswa' => 'MOH. AFIF NASHIRON',
                'no_induk' => '0030155012',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2003-01-08',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'ISMAROH',
            ),
            30 =>
            array (
                'alamat' => 'Tebluru-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 31,
                'jenis_kelamin' => 'Laki-Laki',
                'jurusan' => 2,
                'kelas' => 'Kelas XI',
                'nama_siswa' => 'MOH. BURHANUDDIN',
                'no_induk' => '3011396246',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2001-04-26',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'ISTINAROH',
            ),
            31 =>
            array (
                'alamat' => 'Tebluru-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 32,
                'jenis_kelamin' => 'Laki-Laki',
                'jurusan' => 2,
                'kelas' => 'Kelas XII',
                'nama_siswa' => 'MOH. ERIK FIRMANSYAH',
                'no_induk' => '0022072372',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2002-05-04',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'KHUSNUL KHOTIMAH',
            ),
            32 =>
            array (
                'alamat' => 'Tebluru-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 33,
                'jenis_kelamin' => 'Laki-Laki',
                'jurusan' => 2,
                'kelas' => 'Kelas XII',
                'nama_siswa' => 'Moh. Nashirul Huda',
                'no_induk' => '0022072373',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2002-05-05',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'Rupiyatun',
            ),
            33 =>
            array (
                'alamat' => 'Tebluru-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 34,
                'jenis_kelamin' => 'Laki-Laki',
                'jurusan' => 2,
                'kelas' => 'Kelas XI',
                'nama_siswa' => 'MOH. WAHYUDI',
                'no_induk' => '0022220835',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2002-04-12',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'DARMINI',
            ),
            34 =>
            array (
                'alamat' => 'Tebluru-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 35,
                'jenis_kelamin' => 'Laki-Laki',
                'jurusan' => 2,
                'kelas' => 'Kelas X',
                'nama_siswa' => 'Mohammad Putra Maulana',
                'no_induk' => '0049275802',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2004-08-09',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'Martin Ningrum',
            ),
            35 =>
            array (
                'alamat' => 'Tebluru-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 36,
                'jenis_kelamin' => 'Laki-Laki',
                'jurusan' => 2,
                'kelas' => 'Kelas XI',
                'nama_siswa' => 'MUHAMAD FATCHUR ROHMAN',
                'no_induk' => '0015763336',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2001-12-16',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'SITI MUHAIMIN',
            ),
            36 =>
            array (
                'alamat' => 'Tebluru-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 37,
                'jenis_kelamin' => 'Laki-Laki',
                'jurusan' => 2,
                'kelas' => 'Kelas XII',
                'nama_siswa' => 'MUHAMMAD ALEX',
                'no_induk' => '0023722121',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2002-06-30',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'SUTATIK',
            ),
            37 =>
            array (
                'alamat' => 'Tebluru-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 38,
                'jenis_kelamin' => 'Laki-Laki',
                'jurusan' => 2,
                'kelas' => 'Kelas XII',
                'nama_siswa' => 'MUHAMMAD ALFIN NURUS SALAM',
                'no_induk' => '0007128302',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2000-08-24',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'SITI AISYAH',
            ),
            38 =>
            array (
                'alamat' => 'Tebluru-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 39,
                'jenis_kelamin' => 'Laki-Laki',
                'jurusan' => 2,
                'kelas' => 'Kelas XI',
                'nama_siswa' => 'MUHAMMAD AMIRUDDIN MA\'SUM',
                'no_induk' => '0031188760',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2003-06-20',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'NURHANA',
            ),
            39 =>
            array (
                'alamat' => 'Tebluru-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 40,
                'jenis_kelamin' => 'Laki-Laki',
                'jurusan' => 2,
                'kelas' => 'Kelas XII',
                'nama_siswa' => 'MUHAMMAD ARDIANSYA MAULANA',
                'no_induk' => '0027927171',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2002-05-01',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'DEWI HARTINI',
            ),
            40 =>
            array (
                'alamat' => 'Tebluru-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 41,
                'jenis_kelamin' => 'Laki-Laki',
                'jurusan' => 2,
                'kelas' => 'Kelas XI',
                'nama_siswa' => 'MUHAMMAD FAHMI ZAKARIYA',
                'no_induk' => '3025890005',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2002-08-06',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'TUTIK HIDAYATI',
            ),
            41 =>
            array (
                'alamat' => 'Tebluru-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 42,
                'jenis_kelamin' => 'Laki-Laki',
                'jurusan' => 2,
                'kelas' => 'Kelas XII',
                'nama_siswa' => 'MUHAMMAD MAWAHIBUR ROHMAN',
                'no_induk' => '0016013834',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2001-09-26',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'NURUL HIDAYAH',
            ),
            42 =>
            array (
                'alamat' => 'Tebluru-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 43,
                'jenis_kelamin' => 'Laki-Laki',
                'jurusan' => 2,
                'kelas' => 'Kelas XI',
                'nama_siswa' => 'MUHAMMAD WILDANUL ATQIYA',
                'no_induk' => '0026498471',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2002-10-18',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'SULISTIYANI',
            ),
            43 =>
            array (
                'alamat' => 'Paciran-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 44,
                'jenis_kelamin' => 'Perempuan',
                'jurusan' => 2,
                'kelas' => 'Kelas XII',
                'nama_siswa' => 'MUNTI\'AH',
                'no_induk' => '3011960152',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2001-09-06',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'DASRI',
            ),
            44 =>
            array (
                'alamat' => 'Paciran-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 45,
                'jenis_kelamin' => 'Perempuan',
                'jurusan' => 2,
                'kelas' => 'Kelas XI',
                'nama_siswa' => 'Mutiara Suci Khoirun Nisa\'',
                'no_induk' => '0025891969',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2002-12-13',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'Eni Saidah',
            ),
            45 =>
            array (
                'alamat' => 'Paciran-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 46,
                'jenis_kelamin' => 'Perempuan',
                'jurusan' => 2,
                'kelas' => 'Kelas XI',
                'nama_siswa' => 'NABILATUS SHOLIHAH',
                'no_induk' => '0032538002',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2003-03-04',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'LULUK MAMLUHAH',
            ),
            46 =>
            array (
                'alamat' => 'Paciran-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 47,
                'jenis_kelamin' => 'Perempuan',
                'jurusan' => 2,
                'kelas' => 'Kelas X',
                'nama_siswa' => 'Nada Rifqiyah',
                'no_induk' => '0043430188',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2004-04-21',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'Sholihatin Nur',
            ),
            47 =>
            array (
                'alamat' => 'Paciran-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 48,
                'jenis_kelamin' => 'Perempuan',
                'jurusan' => 2,
                'kelas' => 'Kelas XII',
                'nama_siswa' => 'NAILA FARIHA',
                'no_induk' => '0010818929',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2001-07-25',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'MARWIYAH',
            ),
            48 =>
            array (
                'alamat' => 'Paciran-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 49,
                'jenis_kelamin' => 'Laki-Laki',
                'jurusan' => 2,
                'kelas' => 'Kelas XII',
                'nama_siswa' => 'NASHRUL UMAM',
                'no_induk' => '0015891573',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2001-11-23',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'NAFSAROH',
            ),
            49 =>
            array (
                'alamat' => 'Paciran-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 50,
                'jenis_kelamin' => 'Perempuan',
                'jurusan' => 2,
                'kelas' => 'Kelas XI',
                'nama_siswa' => 'NGRENI MASFUFAH',
                'no_induk' => '0026177924',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2002-07-14',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'WIWIN IRA WATI',
            ),
            50 =>
            array (
                'alamat' => 'Paciran-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 51,
                'jenis_kelamin' => 'Perempuan',
                'jurusan' => 2,
                'kelas' => 'Kelas XI',
                'nama_siswa' => 'Nila Faizatul Maula',
                'no_induk' => '0043415811',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2004-01-21',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'Siti Aisyah',
            ),
            51 =>
            array (
                'alamat' => 'Paciran-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 52,
                'jenis_kelamin' => 'Perempuan',
                'jurusan' => 2,
                'kelas' => 'Kelas XII',
                'nama_siswa' => 'Nur Aeni Azizah',
                'no_induk' => '0020010878',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2002-03-01',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'Rofi\'',
            ),
            52 =>
            array (
                'alamat' => 'Paciran-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 53,
                'jenis_kelamin' => 'Perempuan',
                'jurusan' => 2,
                'kelas' => 'Kelas XI',
                'nama_siswa' => 'Nur Fadlilatus Sania',
                'no_induk' => '0032170800',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2003-07-14',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'Mufarochah',
            ),
            53 =>
            array (
                'alamat' => 'Paciran-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 54,
                'jenis_kelamin' => 'Perempuan',
                'jurusan' => 2,
                'kelas' => 'Kelas XII',
                'nama_siswa' => 'NUR MAHMUDI ISNAENI',
                'no_induk' => '0015891407',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2001-11-28',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'ARIK INDRAWATI',
            ),
            54 =>
            array (
                'alamat' => 'Paciran-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 55,
                'jenis_kelamin' => 'Perempuan',
                'jurusan' => 2,
                'kelas' => 'Kelas XI',
                'nama_siswa' => 'OLIVIA NATANIA',
                'no_induk' => '3982665084',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '1998-10-18',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'SAUDAH',
            ),
            55 =>
            array (
                'alamat' => 'Paciran-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 56,
                'jenis_kelamin' => 'Perempuan',
                'jurusan' => 2,
                'kelas' => 'Kelas XII',
                'nama_siswa' => 'Risa',
                'no_induk' => '0013205147',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2001-07-24',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'Surat',
            ),
            56 =>
            array (
                'alamat' => 'Paciran-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 57,
                'jenis_kelamin' => 'Perempuan',
                'jurusan' => 2,
                'kelas' => 'Kelas XII',
                'nama_siswa' => 'RIZKY ISNAINI MAULIDY',
                'no_induk' => '0027365521',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2002-08-01',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'ZULIANA',
            ),
            57 =>
            array (
                'alamat' => 'Paciran-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 58,
                'jenis_kelamin' => 'Perempuan',
                'jurusan' => 2,
                'kelas' => 'Kelas XII',
                'nama_siswa' => 'Roikhatus Zulfa',
                'no_induk' => '0018692941',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2001-01-23',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'Wasriyah',
            ),
            58 =>
            array (
                'alamat' => 'Paciran-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 59,
                'jenis_kelamin' => 'Perempuan',
                'jurusan' => 2,
                'kelas' => 'Kelas XI',
                'nama_siswa' => 'Sa\'adah Abadiah',
                'no_induk' => '3014180593',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2001-08-05',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'Siti Nur Kholifah',
            ),
            59 =>
            array (
                'alamat' => 'Paciran-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 60,
                'jenis_kelamin' => 'Perempuan',
                'jurusan' => 2,
                'kelas' => 'Kelas X',
                'nama_siswa' => 'Shofiyah',
                'no_induk' => '0049354011',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2004-06-08',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'Maliyah',
            ),
            60 =>
            array (
                'alamat' => 'Paciran-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 61,
                'jenis_kelamin' => 'Perempuan',
                'jurusan' => 2,
                'kelas' => 'Kelas X',
                'nama_siswa' => 'SITI MUTAMIMAH',
                'no_induk' => '0024624570',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2001-10-28',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'SITI ULZIMAH',
            ),
            61 =>
            array (
                'alamat' => 'Paciran-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 62,
                'jenis_kelamin' => 'Perempuan',
                'jurusan' => 2,
                'kelas' => 'Kelas XII',
                'nama_siswa' => 'Siti Riyani',
                'no_induk' => '0023637063',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2002-02-04',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'Marwati',
            ),
            62 =>
            array (
                'alamat' => 'Paciran-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 63,
                'jenis_kelamin' => 'Perempuan',
                'jurusan' => 2,
                'kelas' => 'Kelas XII',
                'nama_siswa' => 'SOVA SEVILIA',
                'no_induk' => '0021641781',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2002-09-28',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'SULISWATI',
            ),
            63 =>
            array (
                'alamat' => 'Paciran-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 64,
                'jenis_kelamin' => 'Laki-Laki',
                'jurusan' => 2,
                'kelas' => 'Kelas XII',
                'nama_siswa' => 'SYAHRUL RAMADAN',
                'no_induk' => '0019130060',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2001-11-12',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'SUSANTI',
            ),
            64 =>
            array (
                'alamat' => 'Paciran-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 65,
                'jenis_kelamin' => 'Perempuan',
                'jurusan' => 2,
                'kelas' => 'Kelas X',
                'nama_siswa' => 'TAUJIDDAH ARGUN',
                'no_induk' => '0012976218',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2001-05-08',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'Kusriyati',
            ),
            65 =>
            array (
                'alamat' => 'Paciran-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 66,
                'jenis_kelamin' => 'Laki-Laki',
                'jurusan' => 2,
                'kelas' => 'Kelas XII',
                'nama_siswa' => 'TEGUH FIRMANSYAH',
                'no_induk' => '0016828133',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2001-05-22',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'DEPA LENI',
            ),
            66 =>
            array (
                'alamat' => 'Paciran-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 67,
                'jenis_kelamin' => 'Perempuan',
                'jurusan' => 2,
                'kelas' => 'Kelas XI',
                'nama_siswa' => 'Umi Fitriani',
                'no_induk' => '0026549910',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2002-12-06',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'Karjumi',
            ),
            67 =>
            array (
                'alamat' => 'Paciran-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 68,
                'jenis_kelamin' => 'Laki-Laki',
                'jurusan' => 2,
                'kelas' => 'Kelas XI',
                'nama_siswa' => 'VANNY ABDUL ADIL BAIN NURKAN',
                'no_induk' => '0032778749',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2003-04-26',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'Giharti',
            ),
            68 =>
            array (
                'alamat' => 'Paciran-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 69,
                'jenis_kelamin' => 'Perempuan',
                'jurusan' => 2,
                'kelas' => 'Kelas X',
                'nama_siswa' => 'WASI\'UL MAGHFIROH',
                'no_induk' => '0037536645',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2003-12-19',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'ANIK FAUZIAH',
            ),
            69 =>
            array (
                'alamat' => 'Paciran-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 70,
                'jenis_kelamin' => 'Perempuan',
                'jurusan' => 2,
                'kelas' => 'Kelas XII',
                'nama_siswa' => 'Waus Saniyah',
                'no_induk' => '0028558052',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2002-05-04',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'Casripah',
            ),
            70 =>
            array (
                'alamat' => 'Paciran-Solokuro-Lamongan',
                'alasan_masuk' => 'Baru',
                'avatar' => NULL,
                'id' => 71,
                'jenis_kelamin' => 'Laki-Laki',
                'jurusan' => 2,
                'kelas' => 'Kelas XII',
                'nama_siswa' => 'Zufar Lazuardi',
                'no_induk' => '0022072374',
                'status_aktif' => 'Active',
                'status_lulus' => NULL,
                'tanggal_keluar' => NULL,
                'tanggal_lahir' => '2002-05-12',
                'tanggal_masuk' => '2020-06-22',
                'tempat_lahir' => 'Lamongan',
                'wali' => 'Siti Rahmatun',
            ),
        ));


    }
}
